name: "RoyaleAPI Ranked Cache"

on:
  schedule:
    - cron: "0 0 * * *" # daily 00:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Fetch ranked matches
        run: |
          python scripts/royaleapi_ranked_cache.py \
            --limit 1000 \
            --rank 1000 \
            --lang en \
            --delay 0.35 \
            --out scripts/royaleapi_ranked_cache.json

      - name: Commit changes
        run: |
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add scripts/royaleapi_ranked_cache.json
            git commit -m "chore: update ranked deck cache"
            git push
          else
            echo "No changes to commit"
          fi
